### PR TITLE
Update all crates to Rust 2018 edition

### PR DESCRIPTION
**Pull request by Atul9**
#64 Update account crate for Rust 2018 using 'cargo fix --edition'

### CODE REVIEW

**Comment by octavonce** [comment]
@Atul9 Hi, and thank you for wishing to contribute to the Purple Protocol! Can you please only include a single PR with all of the changes for #64? Thank you!

**Comment by Atul9** [comment]
Hi @octavonce, done. I have updated the PR.

**Comment by octavonce** [comment]
Using `cargo fix` seems to break quite a lot of stuff. I don't think this is the best approach to this.

**Comment by Atul9** [comment]
@octavonce what approach do you suggest?

**Comment by octavonce** [comment]
@Atul9 Maybe doing it manually?

**Comment by Atul9** [comment]
@octavonce how about we update only those crates for which the build passes using `cargo fix`? `purple_vm` crate can be updated in another PR manually.

**Comment by octavonce** [comment]
@Atul9 As long as the CI check passes, this seems fair. But `cargo fix` does not seem to remove `extern crate` statements? Can you also please remove the `extern crate` statements, rebase the branch, then I believe it is good?

**Comment by Atul9** [comment]
@octavonce yes, I will remove the `extern crate` statements and rebase the branch. I am working on it.

**Comment by Atul9** [comment]
@octavonce I have rebased the branch. Can you please merge this PR then I can remove the `extern crate` statements in another PR

**Pull request closed without merging**
